# This make the data persistent.
volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: 'always'
    ports:
      - "${DB_EXPOSED_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DB_NAME:-postgres}

